kind: Deployment
apiVersion: apps/v1
namespace: roboshop
metadata:
  name: pod
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: Always